P4ProjectWebsite/Models/Queries/EditTask.cs
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;

namespace P4ProjectWebsite.Models.Queries
{
    public class EditTask
    {
        private readonly string ConnectionString;
        public EditTask(IConfiguration configuration)
        {
            ConnectionString = configuration.GetConnectionString("P4Database");
        }
        public void Update(int taskId, string Title, string Description, int Duration, string Location, string Category)
        {
            // connects to the database.
            using (SqlConnection cnn = new SqlConnection(ConnectionString))
            {
                // create a variable with the query command
                string query = $"UPDATE Tasks SET Title = '{Title}', Description ='{Description}', Duration='{Duration}', Location='{Location}', Category='{Category}' WHERE Id = '{taskId}'";

                using (SqlCommand command = new SqlCommand(query, cnn))
                {
                    cnn.Open();
                    int result = command.ExecuteNonQuery();
                    cnn.Close();

                    // Check Error
                    if (result < 0)
                        Console.WriteLine("Error inserting data into Database!");
                }
            }
        }
    }
}

P4ProjectWebsite/Models/Tasks.cs
using System;
using System.Collections.Generic;
using System.Text;

namespace P4ProjectWebsite.Models
{
    public class Tasks
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public int Salary { get; set; }
        public int Duration { get; set; }
        public int Id { get; }
        public string Location { get; set; }
    }
}

P4ProjectWebsite/Controllers/Supplier/AddTaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using P4ProjectWebsite.Models;
using P4ProjectWebsite.Models.Queries;
using Microsoft.AspNetCore.Identity;
using System.Security.Principal;
using System.Security.Claims;

namespace P4ProjectWebsite.Controllers.Supplier
{
    [Authorize(Policy = "SupplierAccess")]
    public class AddTaskController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly UserManager<IdentityUser> _userManager;
        public AddTaskController(IConfiguration configuration, UserManager<IdentityUser> userManager)
        {
            _configuration = configuration;
            _userManager = userManager;

        }
        
        public IActionResult Index()
        {
            var g = new GetCategories(_configuration);
            var CategoryList = g.GetList();
            return View("../Task/Supplier/AddTask" , CategoryList);
        }
        public IActionResult Save()
        {
 
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var q = new SaveTask(_configuration);
            string Username = q.FindUsername(userId); 
            var b = new TaskEntity
            {
                Title = HttpContext.Request.Form["Title"],
                Description = HttpContext.Request.Form["Description"],
                Location = HttpContext.Request.Form["Location"],
                Duration = int.Parse(HttpContext.Request.Form["Duration"]),
                Category = Request.Form["Category"],
                CreatedBy = Username,
                DateCreated = DateTime.Now.ToString("dddd, dd MMMM yyyy")
            };
            
            
            q.InsertTask(b);            
            return RedirectToAction("Index");
        }

    }
}

P4ProjectWebsite/Controllers/Supplier/EditTaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using P4ProjectWebsite.Models.Queries;

namespace P4ProjectWebsite.Controllers.Supplier
{
    public class EditTaskController : Controller
    {
        private readonly IConfiguration _configuration;
        public EditTaskController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Edit(int taskId)
        {
            string Title = HttpContext.Request.Form["Title"];
            string Description = HttpContext.Request.Form["Description"];
            int Duration = int.Parse(HttpContext.Request.Form["Duration"]);
            string Location = HttpContext.Request.Form["Location"];
            string Category = Request.Form["Category"];

            EditTask q = new EditTask(_configuration);

            q.Update(taskId, Title, Description, Duration, Location, Category);

            return RedirectToAction("YourTasks", "YourTask");
        }
    }
}

P4ProjectWebsite/Controllers/Supplier/IncomingBidsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using P4ProjectWebsite.Models;
using P4ProjectWebsite.Models.Queries;

namespace P4ProjectWebsite.Controllers.Supplier
{
    public class IncomingBidsController : Controller
    {
        private readonly IConfiguration _configuration;
        public IncomingBidsController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public IActionResult Index()
        {
            return View("../Task/Bidding/Supplier/ShowIncomingBids");
        }

        public IActionResult ShowIncomingBids(int taskId, string createdBy)
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var b = new GetOpenTasks(_configuration);
            string username = b.FindUsername(userId);
            if (username == createdBy)
            {
            var q = new GetIncomingBids(_configuration);
            var getlist = q.GetList(taskId);
            return View("../Task/Bidding/Supplier/ShowIncomingBids", getlist);
            }
            else { 
            return RedirectToAction("YourTasks", "YourTask");
            }
        }

        public IActionResult Confirm(int bidId, int taskId)
        {
            var q = new ConfirmBid(_configuration);
            q.UpdateBids(bidId);
            q.DeleteBid(taskId);

            if (q.ArchiveTask(taskId))
            {
                q.DeleteTask(taskId);
            }
            
            return RedirectToAction("ShowIncomingBids");
        }
    }
}

P4ProjectWebsite/Controllers/Supplier/SindexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace P4ProjectWebsite.Controllers.Supplier
{
    //[Authorize(Roles = "Supplier")]
    public class SindexController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

P4ProjectWebsite/Controllers/Supplier/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using P4ProjectWebsite.Models;
using P4ProjectWebsite.Models.Queries;
using Microsoft.AspNetCore.Identity;
using System.Security.Principal;
using System.Security.Claims;
using P4ProjectWebsite.Models.Queries;

namespace P4ProjectWebsite.Controllers.Supplier
{
    [Authorize(Policy = "SupplierAccess")]
    public class TaskController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly UserManager<IdentityUser> _userManager;
        public TaskController(IConfiguration configuration, UserManager<IdentityUser> userManager)
        {
            _configuration = configuration;
            _userManager = userManager;

        }
        
        public IActionResult Index()
        {
            var g = new GetCategories(_configuration);
            var CategoryList = g.GetList();
            return View("Supplier/AddTask" , CategoryList);
        }
        public IActionResult Save()
        {
 
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var b = new TaskEntity
            {
                Title = HttpContext.Request.Form["Title"],
                Description = HttpContext.Request.Form["Description"],
                Salary = int.Parse(HttpContext.Request.Form["Salary"]),
                Location = HttpContext.Request.Form["Location"],
                Duration = int.Parse(HttpContext.Request.Form["Duration"]),
                Category = Request.Form["Category"]
            };
            var q = new SaveTask(_configuration);
            //int CategoryId = q.FindCategoryId(Request.Form["Category"]);
            var a = new RelationTaskAddEntity
            {
                Userid = userId,
                //Categoryid = CategoryId
            };
            
            
            q.InsertTask(b);
            q.InsertRelation(a);
            return RedirectToAction("Index");
        }
    }
}

P4ProjectWebsite/Controllers/Supplier/YourTaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using P4ProjectWebsite.Models;
using P4ProjectWebsite.Models.Queries;

namespace P4ProjectWebsite.Controllers.Supplier
{
    public class YourTaskController : Controller
    {
        private readonly IConfiguration _configuration;
        public YourTaskController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Delete(int Id)
        {
            var q = new DeleteTask(_configuration); 
            q.RemoveTask(Id);
            return RedirectToAction("YourTasks");
        }

            public IActionResult EditTask(int Id)
        {
            GetOpenTasks q = new GetOpenTasks(_configuration);
            GetCategories g = new GetCategories(_configuration);
            var CategoryList = g.GetList();
            ViewBag.Task = q.GetSingleTask(Id);
            return View("../Task/Supplier/EditTask", CategoryList);
        }

        public IActionResult YourTasks()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var q = new GetOpenTasks(_configuration);
            string username = q.FindUsername(userId);
            var yourList = q.GetYourList(username);
            var yourArchivedList = q.GetYourArchivedList(username);
            ViewBag.YourList = yourList;
            ViewBag.ArchivedList = yourArchivedList;
            return View("../Task/Supplier/YourTasks");
        }

        
    }
}

P4ProjectWebsite/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using P4ProjectWebsite.Models;
using P4ProjectWebsite.Models.Queries;

namespace P4ProjectWebsite.Controllers
{
    public class TaskController : Controller
    {
        private readonly IConfiguration _configuration;
        public TaskController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult OpenTasks()
        {
            var q = new GetOpenTasks(_configuration);
            return View(q.GetList());
        }
        public IActionResult SingleTask(int id)
        {

            var q = new GetOpenTasks(_configuration);
            var task = q.GetSingleTask(id);
            
           
            return View(task);
        }

        public IActionResult ArchivedTask(int id)
        {
            var q = new GetOpenTasks(_configuration);
            var task = q.GetArchivedTask(id);
            return View(task);
        }

    }
}

P4ProjectWebsite/Views/Task/Supplier/AddTask.cshtml
@model IEnumerable<CategoryEntity>
@{
    ViewData["Title"] = "AddTask";
}
@{var QueryHousekeeping = from Type in Model
                            where Type.Type == "Housekeeping"
                            select Type; }
@{var QueryGarden = from Type in Model
                      where Type.Type == "Garden"
                      select Type; }
@{var QueryMisc = from Type in Model
                    where Type.Type == "Misc"
                    select Type; }

<h1>Create a task</h1>



<div>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</div>
<form asp-controller="AddTask" asp-action="Save" method="post">
    <label for="Title">Task Title:</label><br>
    <input type="text" id="Title" name="Title" placeholder="Write a short description of what your task"required> <br>
    <label for="Description">Task Description:</label><br>
    <input type="text" id="Description" name="Description" placeholder="Describe the task in detail e.g length, height and amount of work that needs to get done."required><br>
    <label for="Duration">Estimated Work Duration:</label><br>
    <input type="number" id="Duration" name="Duration" placeholder="Amount of work hours required" required> Hours<br><br>
    <label for="Location">Location of task:</label><br>
    <input type="text" id="Location" name="Location" placeholder="City, Zipcode, Country"required> <br><br>

    <div id="CategoryContainer">
        <label for="Category"> Task Category: </label>
        <select id="Category" name="Category">
            <option disabled>Choose a category your task fits best in...</option>
            <optgroup label="Housekeeping">
                @foreach (var row in QueryHousekeeping)
                {
                    <option value="@row.Name"> @row.Name </option>
                }
            </optgroup>
            <optgroup label="Garden">
                @foreach (var row in QueryGarden)
                {
                    <option value="@row.Name"> @row.Name </option>
                }
            </optgroup>
            <optgroup label="Miscellaneous">
                @foreach (var row in QueryMisc)
                {
                    <option value="@row.Name"> @row.Name </option>
                }
            </optgroup>
        </select>
    </div>


    <input type="submit" id="SubmitButton1" value="Create Task" />
</form>

P4ProjectWebsite/Views/Task/Supplier/EditTask.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService

@model IEnumerable<CategoryEntity>
@{
    ViewData["Title"] = "EditTask";
}
@{var QueryHousekeeping = from Type in Model
                            where Type.Type == "Housekeeping"
                            select Type; }
@{var QueryGarden = from Type in Model
                      where Type.Type == "Garden"
                      select Type; }
@{var QueryMisc = from Type in Model
                    where Type.Type == "Misc"
                    select Type; }
<title>Edit Task: </title>

@foreach (var row in ViewBag.Task)
{

    <form asp-controller="EditTask" asp-action="Edit" asp-route-taskId="@row.Id" method="post">
        <label for="Title">Task Title:</label>
        <br>
        <input type="text" id="Title" name="Title" value="@row.Title" placeholder="Write a short description of what your task" required>
        <br>
        <label for="Description">Task Description:</label>
        <br>
        <input type="text" id="Description" value="@row.Description" name="Description" placeholder="Describe the task in detail e.g length, height and amount of work that needs to get done." required>
        <br>
        <label for="Duration">Estimated Work Duration:</label>
        <br>
        <input type="number" id="Duration" value="@row.Duration" name="Duration" placeholder="Amount of work hours required" required> Hours
        <br>
        <br>
        <label for="Location">Location of task:</label>
        <br>
        <input type="text" id="Location" value="@row.Location" name="Location" placeholder="City, Zipcode, Country" required>
        <br>

        <br>

        <div id="CategoryContainer">
            <label for="Category"> Task Category: </label>
            <select id="Category" name="Category">
                <option disabled>Choose a category your task fits best in...</option>
                <optgroup label="Housekeeping">
                    @foreach (var cat1 in QueryHousekeeping)
                    {
                        <option value="@cat1.Name"> @cat1.Name </option>
                    }
                </optgroup>
                <optgroup label="Garden">
                    @foreach (var cat2 in QueryGarden)
                    {
                        <option value="@cat2.Name"> @cat2.Name </option>
                    }
                </optgroup>
                <optgroup label="Miscellaneous">
                    @foreach (var cat3 in QueryMisc)
                    {
                        <option value="@cat3.Name"> @cat3.Name </option>
                    }
                </optgroup>
            </select>
        </div>
        <input type="submit" value="Edit" />
    </form>
}

P4ProjectWebsite/Views/Task/Supplier/YourTasks.cshtml
@model IEnumerable<P4ProjectWebsite.Models.TaskEntity>
@{
    ViewData["Title"] = "YourTasks";
}
<meta http-equiv="refresh" content="25" />
<h1>Your active tasks</h1>

<table>
    <thead>

        <tr>
            <th>Title</th>
            <th>Duration</th>
            <th>Location</th>
            <th>Category</th>
            <th>Lowest Bid</th>
            <th>Task Created</th>
            <th>Created by</th>
            
        </tr>
    </thead>
    <tbody>
        @foreach (var row in ViewBag.YourList)
        {
            <tr onclick="location.href = '@(Url.Action("SingleTask", "Task", new { id = row.Id }))'">
                <td>@row.Title</td>
                <td>@row.Duration Hours</td>
                <td>@row.Location</td>
                <td>@row.Category</td>
                @if (@row.LowestBid == 10000)
                {
                    <td>Not yet bid</td>
                }
                else
                {
                    <td>@row.LowestBid DKK</td>
                }
                <td>@row.DateCreated</td>
                <td>@row.CreatedBy</td>
                <td>
                    <a asp-controller="YourTask" asp-action="EditTask" asp-route-Id="@row.Id" onclick="return confirm('Do you want to edit the task: @row.Id?')">Edit</a>
                </td>
                <td>
                    <a asp-controller="IncomingBids" asp-action="ShowIncomingBids" asp-route-taskId="@row.Id" asp-route-createdBy="@row.CreatedBy"> View Bids </a>
                </td>
                <td>
                    <a asp-controller="YourTask" asp-action="Delete" asp-route-Id="@row.Id" onclick="return confirm('Are you sure you want to delete the task: @row.Id?')">Delete</a>
                </td>
            </tr>
        }

    </tbody>
</table>
    <h1>Your archived tasks</h1>

    <table>
        <thead>

            <tr>
                <th>Title</th>
                <th>Duration</th>
                <th>Location</th>
                <th>Category</th>
                
                <th>Task Created</th>
                <th>Created by</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var row in ViewBag.ArchivedList)
            {
                <tr onclick="location.href = '@(Url.Action("ArchivedTask", "Task", new { id = row.Id }))'">
                    <td>@row.Title</td>
                    <td>@row.Duration Hours</td>
                    <td>@row.Location</td>
                    <td>@row.Category</td>                  
                    <td>@row.DateCreated</td>
                    <td>@row.CreatedBy</td>
                    
                </tr>
            }

        </tbody>
    </table>
    <style>
        table, th, td {
            border: solid 1px #bbbbbb;
            border-collapse: collapse;
            padding: 2px;
        }
    </style>